language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
env:
- DJANGO=1.4
- DJANGO=1.5
- DJANGO=1.6
- DJANGO=1.7


install:
- pip install -q Django = $DJANGO
- pip install -r requiments.txt

script: python manage.py test